<a href="https://colab.research.google.com/github/salvarezmeneses/DataScience2020/blob/master/2_Lineal_Algebra_with_python_Basics_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basics Operations
Transposiciòn , Suma de matrices y Escalares.
===============

**Objetivo:**
* El objetivo es realizar operaciones básicos.

* definiremos los elementos bàsicos y su valor.

In [3]:
import numpy as np
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([[[255,255,255],[128,128,128],[80,80,80]],
    [[100,101,102],[103,104,105],[160,170,180]],
    [[190,200,210], [220,230,204], [255,227,238]]])

# Transposición de escalar, vector.

**¿ Que es transponer ?**

* Matemáticamente hablando transponer es cambiar las filas x columnas. (siempre y cuando tengan las mismas dimensiones)

* si tengo una matriz de 3 x 2 , quedara de 2 x 3.

* En python , escribir una transpuesta es usar la función .T

* Las variables que almacenen las transpuestas se denotaran con la _t




In [4]:
# Ejercicio 1: realice la transpuesta del escalar e indica al menos una conclusión.

escalar_t = escalar.T
print(escalar_t)

AttributeError: 'float' object has no attribute 'T'

**conclusion:** El resultado anterior no se ejecutara por que el escalar no tiene ni filas, ni columnas por tanto no se podrá transponer

In [25]:
# Ejercicio 2: realice la transpuesta del escalar e indica al menos una conclusión.

vector = np.array([3,4,5,6])
print(vector.shape)

vector = np.reshape(vector, (vector.shape[0],1))
print("\nVector original ",vector.shape)
print(vector)

vector2 = vector.T
print("\nVector transpuesto ", vector2.shape)
print(vector2)

(4,)

Vector original  (4, 1)
[[3]
 [4]
 [5]
 [6]]

Vector transpuesto  (1, 4)
[[3 4 5 6]]


**conclusion:**  El resultado anterior ejecutara el mismo Vector.





# Transposición de matrices
![texto alternativo](https://66.media.tumblr.com/4bba076e87a9c046323aeeaa42fcbca2/tumblr_inline_p4czceCYRv1r5w51c_1280.gifv)

In [0]:
# Matriz inicial
matriz = np.array([[1,2],[3,4],[5,6]])
print(matriz)
print("La dimensión es: ", matriz.shape)


[[1 2]
 [3 4]
 [5 6]]
La dimensión es:  (3, 2)


In [0]:
# Transposición de Matriz.
matriz_t = matriz.T
print(matriz_t)
print("La dimensión es: ", matriz_t.shape)

[[1 3 5]
 [2 4 6]]
La dimensión es:  (2, 3)


In [0]:
# LA TRANSPUESTA DE UNA MATRIZ TRANSPUESTA , ES LA MATRIZ ORIGINAL
matriz_t_t = matriz_t.T
print(matriz_t_t)

# Se obtiene la misma matriz original.

[[1 2]
 [3 4]
 [5 6]]


# Transposición de tensores.

In [28]:
tensor = np.array([[[255,255,255],[128,128,128],[80,80,80]],
    [[100,101,102],[103,104,105],[160,170,180]],
    [[190,200,210], [220,230,204], [255,227,238]]])
print(tensor)
tensor.shape


[[[255 255 255]
  [128 128 128]
  [ 80  80  80]]

 [[100 101 102]
  [103 104 105]
  [160 170 180]]

 [[190 200 210]
  [220 230 204]
  [255 227 238]]]


(3, 3, 3)

In [29]:
tensor_t = tensor.T
print(tensor_t)
tensor_t.shape

[[[255 100 190]
  [128 103 220]
  [ 80 160 255]]

 [[255 101 200]
  [128 104 230]
  [ 80 170 227]]

 [[255 102 210]
  [128 105 204]
  [ 80 180 238]]]


(3, 3, 3)

In [41]:
tensor2 = np.transpose(tensor, axes=(2,0,1))
tensor2

array([[[255, 128,  80],
        [100, 103, 160],
        [190, 220, 255]],

       [[255, 128,  80],
        [101, 104, 170],
        [200, 230, 227]],

       [[255, 128,  80],
        [102, 105, 180],
        [210, 204, 238]]])

# Suma de matrices.

* La suma de matrices, matematicamente se define cuando se tienen las mismas dimensiones.
* Cuando suma y resta matrices , sus dimensiones deben ser iguales.

![texto alternativo](https://www.ditutor.com/matrices/images/19_1.gif)

In [0]:
# Suma de 2 matrices con igual dimensión.
import numpy as np
A = np.array([[2,0,1],[3,0,0],[5,1,1]])
B = np.array([[1,0,1],[1,2,1],[1,1,0]])
C = A + B
D = A - B 

print('la dimension de A es: ', A.shape)
print('la dimension de B es: ', B.shape)
print("\n")
print('la resta de ambos es:',"\n",D)
print('la suma de ambos es:',"\n",C)


la dimension de A es:  (3, 3)
la dimension de B es:  (3, 3)


la resta de ambos es: 
 [[ 1  0  0]
 [ 2 -2 -1]
 [ 4  0  1]]
la suma de ambos es: 
 [[3 0 2]
 [4 2 1]
 [6 2 1]]


In [0]:
# suma de matriz + Escalar.
import numpy as np

escalar = 5.679
matriz = np.array([[1,2],[3,4],[5,6]])

D = matriz + escalar

print(D)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]


In [0]:
# EJERCICIO 1:  Cree una matriz de 5 x 5 y sumesela a su transpuesta.
# Su codigo aquí.
import numpy as np

# Cree una matriz de 5 x 5
matriz3 = np.array([[1,2,3,4,5],[3,4,7,8,9],[5,6,1,0,2],[7,8,4,3,2],[5,2,3,4,1]])
print(matriz3)
matriz3.shape

matriz3_t = matriz3.T
print('la matriz transpuesta es: ')
print(matriz3.T)

[[1 2 3 4 5]
 [3 4 7 8 9]
 [5 6 1 0 2]
 [7 8 4 3 2]
 [5 2 3 4 1]]
la matriz transpuesta es: 
[[1 3 5 7 5]
 [2 4 6 8 2]
 [3 7 1 4 3]
 [4 8 0 3 4]
 [5 9 2 2 1]]


In [0]:
# suma la matriz por su transpuesta.

E = matriz3 + matriz3_t
print(E)

[[ 2  5  8 11 10]
 [ 5  8 13 16 11]
 [ 8 13  2  4  5]
 [11 16  4  6  6]
 [10 11  5  6  2]]


# Broadcasting: Suma de matrices de diferente dimensiòn.

* El término difusión (broadcasting) describe cómo numpy trata las matrices con diferentes dimensiones. 

* Las partes de la operación broadcasting son: 
- La matriz pequeña
- La matriz grande.

* ¿Como opera?: La matriz más pequeña se repite ( o “transmite”,) a través de la matriz más grande para que tengan las mismas dimensiones.

* La matriz más pequeña se repite.



### Practica Broadcasting

In [42]:
import numpy as np

In [61]:
# Analisis 1 : matriz + vector de diferentes dimensiones
escalar = 5.679
vector = np.array([3,4,5,])             # vector es fila de     3 elementos.
vector = np.reshape(vector, (vector.shape[0],1))
matriz = np.array([[1,2],[3,4],[5,6]])  # matriz tiene filas de 2 elementos.
 
A = vector + matriz

In [62]:
A

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

* **Conclusion matriz + vector :** '''No es posible, tienen diferentes dimensiones (shapes)
solucion: transponer la matrix para cambiar sus dimensiones'''

In [63]:
# Validar dimensiones de matriz.t y Vector
print('la matriz es original es:') 
print(matriz)


print('la matriz Transpuesta es:')
print(matriz.T)
print('el vector es :')
print(vector)


la matriz es original es:
[[1 2]
 [3 4]
 [5 6]]
la matriz Transpuesta es:
[[1 3 5]
 [2 4 6]]
el vector es :
[[3]
 [4]
 [5]]


In [64]:
# Creaciòn de Broadcasting.
A = matriz.T + vector 
print(A)


ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [65]:
A = A.T
A

array([[ 4,  7, 10],
       [ 5,  8, 11]])


* **Conclusiòn Broadcasting** 
* Broadcasting es extender (duplicar) el elemento de menor dimensiòn hasta el de mayor dimensiòn.
* tanto, matriz.T como vector tienen filas de 2 elementos.![texto alternativo]
* la matriz mas pequeña (vector) se repitió.

In [0]:
# Broadcasting con la misma dimensiòn.
C = matriz + 42
print(C)


[[43 44]
 [45 46]
 [47 48]]


In [0]:
# creacion de vector 5 X 5
vector4 = ([10,20,30,40,50])
matriz4 = np.array([[1,2,3,4,5],[3,4,7,8,9],[5,6,1,0,2],[7,8,4,3,2],[5,2,3,4,1]])

D = vector4 + matriz4
print(D)

[[11 22 33 44 55]
 [13 24 37 48 59]
 [15 26 31 40 52]
 [17 28 34 43 52]
 [15 22 33 44 51]]


# Parte 3: Producto Interno o Producto Punto (dot producto) entre dos matrices.

**Producto punto**: 
* Producto Punto es una multiplicación a todos los elementos de la matriz.

$$ H =
\left(\begin{array}{cc} 
1 & 2\\
3 & 4\\
\end{array}\right) I =
\left(\begin{array}{cc} 
11 & 12 \\
13 & 14\\
\end{array}\right)
$$ 


In [0]:
import numpy as np

M1 = np.array([[1,2],[3,4]]) 
M2 = np.array([[11,12],[13,14]]) 

M1_dot = M1.dot(M2)

print('el producto interno es:',"\n", M1_dot ,"\n")


el producto interno es: 
 [[37 40]
 [85 92]] 



# Determinante de una matriz.

Es una multiplcacion 



